name: Build Mod

on:
  push:
    branches: [ 'main' ]
    paths:
      - Fabricc-1.17.1
      - Fabricc-1.18.2
      - Fabricc-1.19.2
      - Fabricc-1.19.4
      - Fabricc-1.20
      - build.gradle
      - gradle.properties
      - settings.gradle
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Check out
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache gradle files
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ./.gradle/loom-cache
          key: ${{ runner.os }}-gradle-${{ hashFiles('*.gradle', 'gradle.properties', '**/*.accesswidener') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set build number
        run: sed -i "s/undefined/$GITHUB_RUN_NUMBER/g" gradle.properties

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew remapJar

      - name: Upload JAR file
        uses: actions/upload-artifact@v4
        with:
          name: PearlTickets-Next
          path: |
            Fabricc-*/build/libs/*.jar
